spring.application.name=projeto

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/bd_api
spring.datasource.username=root
spring.datasource.password=